# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grant R. McDermott
email: gmcdermott@ucsb.edu
description: > # this means to ignore newlines until "baseurl:"
  Postdoctoral scholar
  Bren School of Environmental Science and Management
  University of California Santa Barbara
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://grantmcdermott.github.io/" # the base hostname & protocol for your site
twitter_username: grant_mcdermott
github_username:  grantmcdermott

# Build settings
markdown: kramdown
